test('test', async ({ page }) => {
    await page.goto('http://stackadapt-interview.us-east-1.elasticbeanstalk.com/');
    await page.getByRole('link', { name: 'Sign Up' }).click();
    await page.getByLabel('Name').click();
    await page.getByLabel('Name').fill('TestUser1');
    await page.getByLabel('Email').click();
    await page.getByLabel('Email').fill('TestUser1@gmail.com');
    await page.getByLabel('Email').dblclick();
    await page.getByLabel('Email').click();
    await page.getByLabel('Email').press('ArrowLeft');
    await page.getByLabel('Email').press('ArrowLeft');
    await page.getByLabel('Email').press('ArrowLeft');
    await page.getByLabel('Email').press('ArrowLeft');
    await page.getByLabel('Email').fill('TestUser1@Testmail.com');
    await page.getByLabel('Password').click();
    await page.getByLabel('Password').fill('123456');
    await page.getByLabel('Agree to the Terms of Service').check();
    await page.getByRole('button', { name: 'Sign up' }).click();
    await page.getByRole('link', { name: 'add a task' }).click();
    await page.getByLabel('Your Task').click();
    await page.getByLabel('Your Task').fill('My Test Task is here');
    await page.getByRole('button', { name: 'Save Task' }).click();
    await page.getByRole('link', { name: 'Tasks' }).click();
    await page.getByRole('link', { name: 'Add Task' }).click();
    await page.getByLabel('Your Task').click();
    await page.getByLabel('Your Task').fill('My 2nd test is right here');
    await page.getByRole('button', { name: 'Save Task' }).click();
    await page.getByRole('link', { name: 'Tasks' }).click();
    await page.getByRole('link', { name: 'Add Task' }).click();
    await page.getByLabel('Your Task').click();
    await page.getByLabel('Your Task').fill('I can add my second task');
    await page.getByLabel('Your Task').click();
    await page.getByRole('button', { name: 'Save Task' }).click();
    await page.getByRole('link', { name: 'View' }).first().click();
    await page.getByText('My Test Task is here').click({
      button: 'right'
    });
    await page.getByText('My Test Task is here').click();
    await page.getByText('My Test Task is here 1 minute ago').click();
    await page.getByRole('link', { name: 'Tasks' }).click();
    await page.getByRole('link', { name: 'My Tasks' }).click();
    await page.getByRole('link', { name: 'Edit' }).nth(1).click();
    await page.getByLabel('Your Task').click();
    await page.getByLabel('Your Task').fill('My 2nd test is right here Edited Here');
    await page.getByRole('button', { name: 'Save Task' }).click();
    await page.getByRole('link', { name: 'Delete' }).nth(2).click();
    await page.getByRole('link', { name: 'TestUser1' }).click();
    await page.getByRole('link', { name: 'Update Profile' }).click();
    await page.getByLabel('Name').click();
    await page.getByLabel('Name').fill('TestUser2');
    await page.getByLabel('Email').click();
    await page.getByLabel('Email').click();
    await page.getByLabel('Email').press('ArrowLeft');
    await page.getByLabel('Email').press('ArrowLeft');
    await page.getByLabel('Email').press('ArrowLeft');
    await page.getByLabel('Email').press('ArrowLeft');
    await page.getByLabel('Email').press('ArrowLeft');
    await page.getByLabel('Email').press('ArrowLeft');
    await page.getByLabel('Email').fill('TestUser2@Testmail.com');
    await page.getByRole('button', { name: 'Update' }).click();
    await page.getByText('Profile Successfully Changed! ×').click();
    await page.getByRole('button', { name: '×' }).click();
    await page.getByRole('link', { name: 'Tasks' }).click();
    await page.getByRole('link', { name: 'My Tasks' }).click();
    await page.getByRole('link', { name: 'TestUser2' }).click();
    await page.getByRole('link', { name: 'Change Password' }).click();
    await page.getByLabel('Current password').click();
    await page.getByLabel('Current password').fill('12345678');
    await page.getByLabel('New password').click();
    await page.getByLabel('New password').fill('12345678');
    await page.getByLabel('Current password').dblclick();
    await page.locator('div').filter({ hasText: 'Current password New password Password again Update' }).nth(4).click();
    await page.getByLabel('Current password').click({
      clickCount: 3
    });
    await page.getByLabel('Current password').fill('123456');
    await page.getByLabel('New password').dblclick();
    await page.getByLabel('New password').click();
    await page.getByLabel('New password').fill('1234567');
    await page.getByLabel('Password again').click();
    await page.getByLabel('Password again').fill('1234567');
    await page.getByRole('button', { name: 'Update' }).click();
    await page.getByText('Password updated. ×').click();
    await page.getByRole('button', { name: '×' }).click();
    await page.getByRole('link', { name: 'TestUser2' }).click();
    await page.getByRole('link', { name: 'Logout' }).click();
    await page.getByText('Logged out ×').click();
    await page.getByRole('heading', { name: 'Welcome to the StackTodo application, we hope you enjoy working on this assignment!' }).click();
    await page.getByRole('button', { name: '×' }).click();
  });